apiVersion: apps/v1
kind: Deployment
metadata:
  name: websockets-deployment
  labels:
    app: websockets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: websockets
  template:
    metadata:
      labels:
        app: websockets
    spec:
      containers:
        - name: websockets
          image: 719220092744.dkr.ecr.eu-west-3.amazonaws.com/websocktes-repo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ConnectionStrings__FleetManagementDb
              valueFrom:
                  configMapKeyRef:
                    name: mongo-configmap
                    key: connection_string
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: websockets-service
  # namespace: eksfargateapp
  # labels:
  #   app: my-app
spec:
  type: LoadBalancer
  selector:
    app: websockets
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
